name: Notify

on: push

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Push通知"
          body: "GitHubにpushされました"
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}